"""
Data exploration script for HackerRank Orchestrate knowledge base.
Run from repo root: python code/explore.py
Outputs: data_exploration_report.md
"""

import os
import csv
import json
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).parent.parent
DATA_DIR = REPO_ROOT / "data"
TICKETS_DIR = REPO_ROOT / "support_tickets"
REPORT_PATH = REPO_ROOT / "data_exploration_report.md"

COMPANIES = ["hackerrank", "claude", "visa"]


def human_size(num_bytes: int) -> str:
    for unit in ("B", "KB", "MB"):
        if num_bytes < 1024:
            return f"{num_bytes:.1f} {unit}"
        num_bytes /= 1024
    return f"{num_bytes:.1f} GB"


def word_count(text: str) -> int:
    return len(text.split())


def scan_company(company: str) -> dict:
    base = DATA_DIR / company
    if not base.exists():
        return {}

    result = {
        "company": company,
        "total_files": 0,
        "total_bytes": 0,
        "total_words": 0,
        "product_areas": defaultdict(lambda: {"files": 0, "bytes": 0, "words": 0, "headings": []}),
    }

    for root, dirs, files in os.walk(base):
        dirs.sort()
        md_files = [f for f in files if f.endswith(".md")]
        if not md_files:
            continue

        rel = Path(root).relative_to(base)
        area_key = str(rel) if str(rel) != "." else "(root)"

        for fname in sorted(md_files):
            fpath = Path(root) / fname
            try:
                text = fpath.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue

            size = fpath.stat().st_size
            wc = word_count(text)

            result["total_files"] += 1
            result["total_bytes"] += size
            result["total_words"] += wc

            area = result["product_areas"][area_key]
            area["files"] += 1
            area["bytes"] += size
            area["words"] += wc

            # Collect H1/H2 headings as topic signals
            headings = [
                line.lstrip("#").strip()
                for line in text.splitlines()
                if line.startswith("#") and not line.startswith("####")
            ]
            area["headings"].extend(headings[:3])

    return result


def analyze_csv(path: Path) -> dict:
    if not path.exists():
        return {"error": f"{path} not found"}

    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames or []
        for row in reader:
            rows.append(row)

    stats: dict = {
        "path": str(path.relative_to(REPO_ROOT)),
        "row_count": len(rows),
        "columns": fieldnames,
    }

    if "Company" in fieldnames:
        companies = defaultdict(int)
        for r in rows:
            companies[r.get("Company", "").strip()] += 1
        stats["companies"] = dict(sorted(companies.items()))

    if "Product Area" in fieldnames:
        areas = defaultdict(int)
        for r in rows:
            areas[r.get("Product Area", "").strip()] += 1
        stats["product_areas"] = dict(sorted(areas.items()))

    if "Request Type" in fieldnames:
        rtypes = defaultdict(int)
        for r in rows:
            rtypes[r.get("Request Type", "").strip()] += 1
        stats["request_types"] = dict(sorted(rtypes.items()))

    if "Status" in fieldnames:
        statuses = defaultdict(int)
        for r in rows:
            statuses[r.get("Status", "").strip()] += 1
        stats["statuses"] = dict(sorted(statuses.items()))

    return stats


def build_report(company_data: list[dict], csv_stats: list[dict]) -> str:
    lines = []
    lines.append("# Data Exploration Report — HackerRank Orchestrate\n")
    lines.append("> Generated by `code/explore.py`\n")

    # ── Summary Table ────────────────────────────────────────────────────────
    lines.append("## 1. Knowledge Base Summary\n")
    lines.append("| Company | Files | Size | Words | Top-level Areas |")
    lines.append("|---------|-------|------|-------|-----------------|")
    for cd in company_data:
        if not cd:
            continue
        top = sorted(
            {k.split("/")[0] for k in cd["product_areas"] if k != "(root)"}
        )
        lines.append(
            f"| **{cd['company'].title()}** "
            f"| {cd['total_files']} "
            f"| {human_size(cd['total_bytes'])} "
            f"| {cd['total_words']:,} "
            f"| {', '.join(top) if top else '—'} |"
        )
    lines.append("")

    # ── Per-company product area breakdown ───────────────────────────────────
    for cd in company_data:
        if not cd:
            continue
        company = cd["company"].title()
        lines.append(f"## 2. {company} — Product Areas\n")
        lines.append("| Product Area | Files | Size | Words | Sample Topics |")
        lines.append("|-------------|-------|------|-------|---------------|")

        for area_key in sorted(cd["product_areas"]):
            area = cd["product_areas"][area_key]
            # Deduplicate + trim headings sample
            seen: set[str] = set()
            unique_headings = []
            for h in area["headings"]:
                if h and h not in seen:
                    seen.add(h)
                    unique_headings.append(h)
                if len(unique_headings) >= 3:
                    break
            sample = " · ".join(unique_headings) if unique_headings else "—"
            lines.append(
                f"| `{area_key}` "
                f"| {area['files']} "
                f"| {human_size(area['bytes'])} "
                f"| {area['words']:,} "
                f"| {sample} |"
            )
        lines.append("")

    # ── CSV Analysis ─────────────────────────────────────────────────────────
    lines.append("## 3. Support Ticket CSV Analysis\n")
    for stats in csv_stats:
        if "error" in stats:
            lines.append(f"- **{stats.get('path', '?')}**: {stats['error']}\n")
            continue

        lines.append(f"### `{stats['path']}`\n")
        lines.append(f"- **Rows**: {stats['row_count']}")
        lines.append(f"- **Columns**: {', '.join(f'`{c}`' for c in stats['columns'])}\n")

        if "companies" in stats:
            lines.append("**Ticket distribution by company:**\n")
            lines.append("| Company | Count |")
            lines.append("|---------|-------|")
            for k, v in stats["companies"].items():
                lines.append(f"| {k or '(blank)'} | {v} |")
            lines.append("")

        if "product_areas" in stats:
            lines.append("**Unique product areas:**\n")
            lines.append("| Product Area | Count |")
            lines.append("|-------------|-------|")
            for k, v in sorted(stats["product_areas"].items(), key=lambda x: -x[1]):
                lines.append(f"| {k or '(blank)'} | {v} |")
            lines.append("")

        if "request_types" in stats:
            lines.append("**Request type distribution:**\n")
            lines.append("| Request Type | Count |")
            lines.append("|-------------|-------|")
            for k, v in sorted(stats["request_types"].items(), key=lambda x: -x[1]):
                lines.append(f"| {k or '(blank)'} | {v} |")
            lines.append("")

        if "statuses" in stats:
            lines.append("**Status distribution:**\n")
            lines.append("| Status | Count |")
            lines.append("|--------|-------|")
            for k, v in sorted(stats["statuses"].items(), key=lambda x: -x[1]):
                lines.append(f"| {k or '(blank)'} | {v} |")
            lines.append("")

    # ── Full file tree ────────────────────────────────────────────────────────
    lines.append("## 4. Full File Tree\n")
    for company in COMPANIES:
        base = DATA_DIR / company
        if not base.exists():
            continue
        lines.append(f"### `data/{company}/`\n")
        lines.append("```")
        for root, dirs, files in os.walk(base):
            dirs.sort()
            depth = len(Path(root).relative_to(base).parts)
            indent = "    " * depth
            folder_name = Path(root).name
            if depth == 0:
                lines.append(f"{company}/")
            else:
                lines.append(f"{indent}{folder_name}/")
            for fname in sorted(f for f in files if f.endswith(".md")):
                lines.append(f"{indent}    {fname}")
        lines.append("```\n")

    return "\n".join(lines)


def main():
    print("Scanning knowledge base...")
    company_data = []
    for company in COMPANIES:
        print(f"  → {company}...", end=" ", flush=True)
        cd = scan_company(company)
        company_data.append(cd)
        if cd:
            print(f"{cd['total_files']} files, {human_size(cd['total_bytes'])}")
        else:
            print("not found")

    print("\nAnalyzing support ticket CSVs...")
    csv_stats = []
    for fname in ["sample_support_tickets.csv", "support_tickets.csv"]:
        path = TICKETS_DIR / fname
        print(f"  → {fname}...", end=" ", flush=True)
        stats = analyze_csv(path)
        csv_stats.append(stats)
        print(f"{stats.get('row_count', '?')} rows")

    print("\nBuilding report...")
    report = build_report(company_data, csv_stats)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Report saved to: {REPORT_PATH.relative_to(REPO_ROOT)}")

    # Print a quick console summary
    print("\n" + "=" * 60)
    print("KNOWLEDGE BASE QUICK SUMMARY")
    print("=" * 60)
    for cd in company_data:
        if cd:
            print(f"{cd['company'].upper():12s}  {cd['total_files']:4d} files  "
                  f"{human_size(cd['total_bytes']):8s}  {cd['total_words']:>7,} words")
    print("=" * 60)


if __name__ == "__main__":
    main()
